version: '3.8'

services:
  app:
    build: .
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env
    command: >
      sh -c "yarn prisma generate && yarn start:dev"
